version: '3.7'

services:
  pega-pe-frontend:
    container_name: pega-pe-frontend
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./pega-pe-frontend
    depends_on:
      - pega-pe-backend
    environment:
      - JDBC_URL=jdbc:postgresql://pega-pe-backend/${POSTGRES_DB}?raiseExceptionOnSilentRollback=false
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=5432
      - JDBC_DRIVER_URI=https://jdbc.postgresql.org/download/postgresql-42.3.4.jar
      - JDBC_CLASS=org.postgresql.Driver
    ports:
      - "8080"

  pega-pe-backend:
    container_name: pega-pe-backend
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./pega-pe-backend
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
