version: '3.7'

services:
  backend:
    image: image_pega-pe-backend:latest
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      
  frontend:
    image: image_pega-pe-frontend:latest
    depends_on:
      - backend
    environment:
      - JDBC_URL=jdbc:postgresql://pega-pe-backend/postgres?raiseExceptionOnSilentRollback=false
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - JDBC_DRIVER_URI=https://jdbc.postgresql.org/download/postgresql-42.3.4.jar
      - JDBC_CLASS=org.postgresql.Driver
    ports:
      - "9002:8080"
